### ISSUE TITLE
Username and Password Required

### ISSUE THREAD

**Issue by goncalofurtado1** [AnasIbrahim/image_agnostic_segmentation#1]
Hello,

I am trying to use the image_agnostic_segmentation tool for a project I'm working on and I have so far successfully build the catkin workspace although I had to change the `#!/usr/bin/env python` to `#!/usr/bin/env python3` in both the **segmentation_test** and the **bring_up_node** python files. When executing the **roslaunch** command I got this error message:

![Error1](https://user-images.githubusercontent.com/73246223/165291175-03dcdd45-4448-440e-bd1e-a9a85880bfc9.png)

From it I understood it was because I hadn't done the `git clone https://github.com/FLW-TUDO/image_agnostic_segmentation.git` and I hadn't done it because whenever I did it requested a **username and a password** like so:

![Error2](https://user-images.githubusercontent.com/73246223/165291786-58871515-7a34-49a7-a91e-29407144a846.png)

Of course I had to try and put my own but obviously it didn't work. I don't know if there is anything I am doing wrong or in fact I don't have permission to clone the repository. If it's the former I kindly request help to resolve it. If its the latter I would like to ask for permission to utilize the repository since I find this work best suits the needs for my project. 

Thank You very much for any answer.

**Comment by AnasIbrahim** [comment]
The first error you had is because you didn't download the model (FAT_trained_Ml2R_bin_fine_tuned.pth) or downloaded it in the wrong folder.

This repo is actually public so anyone has the permission to clone it.

**Comment by AnasIbrahim** [comment]
I realized that the model installation instructions for ROS were missing so I added them.

**Comment by AnasIbrahim** [comment]
Also to clone please use:
```
git clone https://github.com/AnasIbrahim/image_agnostic_segmentation.git
```
Now everything looks fine. You can try the installation again.

**Comment by goncalofurtado1** [comment]
Very nice, Thank You for your answer! I'll try the installation again and if all goes well I'll close this issue.
