### ISSUE TITLE
HOPE masks

### ISSUE THREAD

**Issue by RBT22** [AnasIbrahim/image_agnostic_segmentation#2]
Hi,
very nice repo thank you for your work! I was wondering if you could share the instance masks of the HOPE dataset, or the code that you used for the evaluation. I'm a little stuck and you probably already generated the masks from the BOP annotation.

Thank you again!🙌

**Comment by AnasIbrahim** [comment]
Hi,

Do you mean the COCO annotations? This is already supported in the BOP toolkit.
https://github.com/thodan/bop_toolkit/blob/master/scripts/calc_gt_coco.py
This script can convert datasets from the BOP format to COCO.

**Comment by RBT22** [comment]
Thanks for the quick response! I was able to generate the masks with the library.
